# https://github.com/travis-ci/travis-ci/wiki/.travis.yml-options
bundler_args: --without development
script: "bundle exec rake spec:ci"
before_script: ./bin/ci/before_build.sh
rvm:
  - 1.8.7
  - rbx-18mode
  # - rbx-19mode
  - jruby-18mode
  # - jruby-18mode
  - 1.9.2
  - 1.9.3
  # - ruby-head
gemfile:
  - Gemfile
  - gemfiles/eventmachine-pre
notifications:
  recipients:
    - michaelklishin@me.com
branches:
  only:
    - master
    - 0.9.x-stable
    - 0.8.x-stable
    - 0.7.x-stable